//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace zextdevapp1
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class zextbase1Class : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект zextbase1Class, используя строку соединения из раздела "zextbase1Class" файла конфигурации приложения.
        /// </summary>
        public zextbase1Class() : base("name=zextbase1Class", "zextbase1Class")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта zextbase1Class.
        /// </summary>
        public zextbase1Class(string connectionString) : base(connectionString, "zextbase1Class")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта zextbase1Class.
        /// </summary>
        public zextbase1Class(EntityConnection connection) : base(connection, "zextbase1Class")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<notebook> notebooks
        {
            get
            {
                if ((_notebooks == null))
                {
                    _notebooks = base.CreateObjectSet<notebook>("notebooks");
                }
                return _notebooks;
            }
        }
        private ObjectSet<notebook> _notebooks;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<phone> phoneНабор
        {
            get
            {
                if ((_phoneНабор == null))
                {
                    _phoneНабор = base.CreateObjectSet<phone>("phoneНабор");
                }
                return _phoneНабор;
            }
        }
        private ObjectSet<phone> _phoneНабор;

        #endregion

        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet notebooks. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTonotebooks(notebook notebook)
        {
            base.AddObject("notebooks", notebook);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet phoneНабор. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTophoneНабор(phone phone)
        {
            base.AddObject("phoneНабор", phone);
        }

        #endregion

    }

    #endregion

    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zextbase1Model", Name="notebook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class notebook : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта notebook.
        /// </summary>
        /// <param name="id">Исходное значение свойства id.</param>
        /// <param name="firm">Исходное значение свойства firm.</param>
        /// <param name="model">Исходное значение свойства model.</param>
        /// <param name="price">Исходное значение свойства price.</param>
        /// <param name="notebook_diagonalsize">Исходное значение свойства notebook_diagonalsize.</param>
        /// <param name="notebook_usbs">Исходное значение свойства notebook_usbs.</param>
        public static notebook Createnotebook(global::System.Int32 id, global::System.String firm, global::System.String model, global::System.Decimal price, global::System.Decimal notebook_diagonalsize, global::System.Int32 notebook_usbs)
        {
            notebook notebook = new notebook();
            notebook.id = id;
            notebook.firm = firm;
            notebook.model = model;
            notebook.price = price;
            notebook.notebook_diagonalsize = notebook_diagonalsize;
            notebook.notebook_usbs = notebook_usbs;
            return notebook;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firm
        {
            get
            {
                return _firm;
            }
            set
            {
                OnfirmChanging(value);
                ReportPropertyChanging("firm");
                _firm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firm");
                OnfirmChanged();
            }
        }
        private global::System.String _firm;
        partial void OnfirmChanging(global::System.String value);
        partial void OnfirmChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal notebook_diagonalsize
        {
            get
            {
                return _notebook_diagonalsize;
            }
            set
            {
                Onnotebook_diagonalsizeChanging(value);
                ReportPropertyChanging("notebook_diagonalsize");
                _notebook_diagonalsize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("notebook_diagonalsize");
                Onnotebook_diagonalsizeChanged();
            }
        }
        private global::System.Decimal _notebook_diagonalsize;
        partial void Onnotebook_diagonalsizeChanging(global::System.Decimal value);
        partial void Onnotebook_diagonalsizeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 notebook_usbs
        {
            get
            {
                return _notebook_usbs;
            }
            set
            {
                Onnotebook_usbsChanging(value);
                ReportPropertyChanging("notebook_usbs");
                _notebook_usbs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("notebook_usbs");
                Onnotebook_usbsChanged();
            }
        }
        private global::System.Int32 _notebook_usbs;
        partial void Onnotebook_usbsChanging(global::System.Int32 value);
        partial void Onnotebook_usbsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zextbase1Model", Name="phone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class phone : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта phone.
        /// </summary>
        /// <param name="id">Исходное значение свойства id.</param>
        /// <param name="firm">Исходное значение свойства firm.</param>
        /// <param name="model">Исходное значение свойства model.</param>
        /// <param name="price">Исходное значение свойства price.</param>
        /// <param name="phone_battery">Исходное значение свойства phone_battery.</param>
        /// <param name="phone_sim">Исходное значение свойства phone_sim.</param>
        public static phone Createphone(global::System.Int32 id, global::System.String firm, global::System.String model, global::System.Decimal price, global::System.Int32 phone_battery, global::System.String phone_sim)
        {
            phone phone = new phone();
            phone.id = id;
            phone.firm = firm;
            phone.model = model;
            phone.price = price;
            phone.phone_battery = phone_battery;
            phone.phone_sim = phone_sim;
            return phone;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firm
        {
            get
            {
                return _firm;
            }
            set
            {
                OnfirmChanging(value);
                ReportPropertyChanging("firm");
                _firm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firm");
                OnfirmChanged();
            }
        }
        private global::System.String _firm;
        partial void OnfirmChanging(global::System.String value);
        partial void OnfirmChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 phone_battery
        {
            get
            {
                return _phone_battery;
            }
            set
            {
                Onphone_batteryChanging(value);
                ReportPropertyChanging("phone_battery");
                _phone_battery = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("phone_battery");
                Onphone_batteryChanged();
            }
        }
        private global::System.Int32 _phone_battery;
        partial void Onphone_batteryChanging(global::System.Int32 value);
        partial void Onphone_batteryChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone_sim
        {
            get
            {
                return _phone_sim;
            }
            set
            {
                Onphone_simChanging(value);
                ReportPropertyChanging("phone_sim");
                _phone_sim = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone_sim");
                Onphone_simChanged();
            }
        }
        private global::System.String _phone_sim;
        partial void Onphone_simChanging(global::System.String value);
        partial void Onphone_simChanged();

        #endregion

    
    }

    #endregion

    
}
